name: JHipster CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and test application
        run: |
          ./gradlew clean test
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/reports/jacoco/

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build application
        run: |
          ./gradlew clean assemble -Pprod -x test

      - name: Build Docker image
        run: |
          docker build -t jhipster-app:latest .

      - name: Deploy to staging
        run: |
          docker-compose -f src/main/docker/app.yml up -d
